from pydantic import BaseModel, Field, ConfigDict, RootModel, field_validator
import math

from tdd.erros import DadosInvalidos


class ExemploInt(BaseModel):
    nome: str
    valor: int | None = None


class DadosExemplo(list[ExemploInt]):
    ...


def valida_valores_vazios(cls, value):
    if value is not None and math.isnan(value):
        raise DadosInvalidos('Dados na planilha inválidos')
    return value


class DadosPorSemestre(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    dias: int | None = Field(default=None, alias='Dias')
    s_16_1: int | None = Field(default=None, alias='16.1')
    s_16_2: int | None = Field(default=None, alias='16.2')
    s_17_1: int | None = Field(default=None, alias='17.1')
    s_17_2: int | None = Field(default=None, alias='17.2')
    s_18_1: int | None = Field(default=None, alias='18.1')
    s_18_2: int | None = Field(default=None, alias='18.2')
    s_19_1: int | None = Field(default=None, alias='19.1')
    s_19_2: int | None = Field(default=None, alias='19.2')
    s_20_1: int | None = Field(default=None, alias='20.1')
    s_20_2: int | None = Field(default=None, alias='20.2')
    s_21_1: int | None = Field(default=None, alias='21.1')
    s_21_2: int | None = Field(default=None, alias='21.2')
    s_22_1: int | None = Field(default=None, alias='22.1')
    s_22_2: int | None = Field(default=None, alias='22.2')
    s_23_1: int | None = Field(default=None, alias='23.1')
    s_23_2: int | None = Field(default=None, alias='23.2')
    s_24_1: int | None = Field(default=None, alias='24.1')
    s_24_2: int | None = Field(default=None, alias='24.2')
    s_25_1: int | None = Field(default=None, alias='25.1')
    s_25_2: int | None = Field(default=None, alias='25.2')
    s_26_1: int | None = Field(default=None, alias='26.1')
    s_26_2: int | None = Field(default=None, alias='26.2')
    s_27_1: int | None = Field(default=None, alias='27.1')
    s_27_2: int | None = Field(default=None, alias='27.2')
    s_28_1: int | None = Field(default=None, alias='28.1')
    s_28_2: int | None = Field(default=None, alias='28.2')
    s_29_1: int | None = Field(default=None, alias='29.1')
    s_29_2: int | None = Field(default=None, alias='29.2')
    s_30_1: int | None = Field(default=None, alias='30.1')
    s_30_2: int | None = Field(default=None, alias='30.2')

    __pydantic_validator__ = field_validator("*", mode='before')(valida_valores_vazios)


class DadosSemi(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    dias: int | None = Field(default=None, alias='Dias')
    s_18_2_semi_cal_cap: int | None = Field(default=None, alias='18.2 SEMI CAL CAP')
    s_18_2_semi_cal_vig: int | None = Field(default=None, alias='18.2 SEMI CAL VIG')
    s_18_2_semi_cal_eva: int | None = Field(default=None, alias='18.2 SEMI CAL EVA')
    s_18_2_semi_oin_cap: int | None = Field(default=None, alias='18.2 SEMI OIN CAP')
    s_18_2_semi_oin_vig: int | None = Field(default=None, alias='18.2 SEMI OIN VIG')
    s_18_2_semi_oin_eva: int | None = Field(default=None, alias='18.2 SEMI OIN EVA')
    s_18_2_semi_rmt_cap: int | None = Field(default=None, alias='18.2 SEMI RMT CAP')
    s_18_2_semi_rmt_vig: int | None = Field(default=None, alias='18.2 SEMI RMT VIG')
    s_18_2_semi_rmt_eva: int | None = Field(default=None, alias='18.2 SEMI RMT EVA')
    s_19_1_semi_cal_cap: int | None = Field(default=None, alias='19.1 SEMI CAL CAP')
    s_19_1_semi_cal_vig: int | None = Field(default=None, alias='19.1 SEMI CAL VIG')
    s_19_1_semi_cal_eva: int | None = Field(default=None, alias='19.1 SEMI CAL EVA')
    s_19_1_semi_oin_cap: int | None = Field(default=None, alias='19.1 SEMI OIN CAP')
    s_19_1_semi_oin_vig: int | None = Field(default=None, alias='19.1 SEMI OIN VIG')
    s_19_1_semi_oin_eva: int | None = Field(default=None, alias='19.1 SEMI OIN EVA')
    s_19_1_semi_rmt_cap: int | None = Field(default=None, alias='19.1 SEMI RMT CAP')
    s_19_1_semi_rmt_vig: int | None = Field(default=None, alias='19.1 SEMI RMT VIG')
    s_19_1_semi_rmt_eva: int | None = Field(default=None, alias='19.1 SEMI RMT EVA')
    s_19_2_semi_cal_cap: int | None = Field(default=None, alias='19.2 SEMI CAL CAP')
    s_19_2_semi_cal_vig: int | None = Field(default=None, alias='19.2 SEMI CAL VIG')
    s_19_2_semi_cal_eva: int | None = Field(default=None, alias='19.2 SEMI CAL EVA')
    s_19_2_semi_oin_cap: int | None = Field(default=None, alias='19.2 SEMI OIN CAP')
    s_19_2_semi_oin_vig: int | None = Field(default=None, alias='19.2 SEMI OIN VIG')
    s_19_2_semi_oin_eva: int | None = Field(default=None, alias='19.2 SEMI OIN EVA')
    s_19_2_semi_rmt_cap: int | None = Field(default=None, alias='19.2 SEMI RMT CAP')
    s_19_2_semi_rmt_vig: int | None = Field(default=None, alias='19.2 SEMI RMT VIG')
    s_19_2_semi_rmt_eva: int | None = Field(default=None, alias='19.2 SEMI RMT EVA')
    s_20_1_semi_cal_cap: int | None = Field(default=None, alias='20.1 SEMI CAL CAP')
    s_20_1_semi_cal_vig: int | None = Field(default=None, alias='20.1 SEMI CAL VIG')
    s_20_1_semi_cal_eva: int | None = Field(default=None, alias='20.1 SEMI CAL EVA')
    s_20_1_semi_oin_cap: int | None = Field(default=None, alias='20.1 SEMI OIN CAP')
    s_20_1_semi_oin_vig: int | None = Field(default=None, alias='20.1 SEMI OIN VIG')
    s_20_1_semi_oin_eva: int | None = Field(default=None, alias='20.1 SEMI OIN EVA')
    s_20_1_semi_rmt_cap: int | None = Field(default=None, alias='20.1 SEMI RMT CAP')
    s_20_1_semi_rmt_vig: int | None = Field(default=None, alias='20.1 SEMI RMT VIG')
    s_20_1_semi_rmt_eva: int | None = Field(default=None, alias='20.1 SEMI RMT EVA')
    s_20_2_semi_cal_cap: int | None = Field(default=None, alias='20.2 SEMI CAL CAP')
    s_20_2_semi_cal_vig: int | None = Field(default=None, alias='20.2 SEMI CAL VIG')
    s_20_2_semi_cal_eva: int | None = Field(default=None, alias='20.2 SEMI CAL EVA')
    s_20_2_semi_oin_cap: int | None = Field(default=None, alias='20.2 SEMI OIN CAP')
    s_20_2_semi_oin_vig: int | None = Field(default=None, alias='20.2 SEMI OIN VIG')
    s_20_2_semi_oin_eva: int | None = Field(default=None, alias='20.2 SEMI OIN EVA')
    s_20_2_semi_rmt_cap: int | None = Field(default=None, alias='20.2 SEMI RMT CAP')
    s_20_2_semi_rmt_vig: int | None = Field(default=None, alias='20.2 SEMI RMT VIG')
    s_20_2_semi_rmt_eva: int | None = Field(default=None, alias='20.2 SEMI RMT EVA')
    s_21_1_semi_cal_cap: int | None = Field(default=None, alias='21.1 SEMI CAL CAP')
    s_21_1_semi_cal_vig: int | None = Field(default=None, alias='21.1 SEMI CAL VIG')
    s_21_1_semi_cal_eva: int | None = Field(default=None, alias='21.1 SEMI CAL EVA')
    s_21_1_semi_oin_cap: int | None = Field(default=None, alias='21.1 SEMI OIN CAP')
    s_21_1_semi_oin_vig: int | None = Field(default=None, alias='21.1 SEMI OIN VIG')
    s_21_1_semi_oin_eva: int | None = Field(default=None, alias='21.1 SEMI OIN EVA')
    s_21_1_semi_rmt_cap: int | None = Field(default=None, alias='21.1 SEMI RMT CAP')
    s_21_1_semi_rmt_vig: int | None = Field(default=None, alias='21.1 SEMI RMT VIG')
    s_21_1_semi_rmt_eva: int | None = Field(default=None, alias='21.1 SEMI RMT EVA')
    s_21_2_semi_cal_cap: int | None = Field(default=None, alias='21.2 SEMI CAL CAP')
    s_21_2_semi_cal_vig: int | None = Field(default=None, alias='21.2 SEMI CAL VIG')
    s_21_2_semi_cal_eva: int | None = Field(default=None, alias='21.2 SEMI CAL EVA')
    s_21_2_semi_oin_cap: int | None = Field(default=None, alias='21.2 SEMI OIN CAP')
    s_21_2_semi_oin_vig: int | None = Field(default=None, alias='21.2 SEMI OIN VIG')
    s_21_2_semi_oin_eva: int | None = Field(default=None, alias='21.2 SEMI OIN EVA')
    s_21_2_semi_rmt_cap: int | None = Field(default=None, alias='21.2 SEMI RMT CAP')
    s_21_2_semi_rmt_vig: int | None = Field(default=None, alias='21.2 SEMI RMT VIG')
    s_21_2_semi_rmt_eva: int | None = Field(default=None, alias='21.2 SEMI RMT EVA')
    s_22_1_semi_cal_cap: int | None = Field(default=None, alias='22.1 SEMI CAL CAP')
    s_22_1_semi_cal_vig: int | None = Field(default=None, alias='22.1 SEMI CAL VIG')
    s_22_1_semi_cal_eva: int | None = Field(default=None, alias='22.1 SEMI CAL EVA')
    s_22_1_semi_oin_cap: int | None = Field(default=None, alias='22.1 SEMI OIN CAP')
    s_22_1_semi_oin_vig: int | None = Field(default=None, alias='22.1 SEMI OIN VIG')
    s_22_1_semi_oin_eva: int | None = Field(default=None, alias='22.1 SEMI OIN EVA')
    s_22_1_semi_rmt_cap: int | None = Field(default=None, alias='22.1 SEMI RMT CAP')
    s_22_1_semi_rmt_vig: int | None = Field(default=None, alias='22.1 SEMI RMT VIG')
    s_22_1_semi_rmt_eva: int | None = Field(default=None, alias='22.1 SEMI RMT EVA')
    s_22_2_semi_cal_cap: int | None = Field(default=None, alias='22.2 SEMI CAL CAP')
    s_22_2_semi_cal_vig: int | None = Field(default=None, alias='22.2 SEMI CAL VIG')
    s_22_2_semi_cal_eva: int | None = Field(default=None, alias='22.2 SEMI CAL EVA')
    s_22_2_semi_oin_cap: int | None = Field(default=None, alias='22.2 SEMI OIN CAP')
    s_22_2_semi_oin_vig: int | None = Field(default=None, alias='22.2 SEMI OIN VIG')
    s_22_2_semi_oin_eva: int | None = Field(default=None, alias='22.2 SEMI OIN EVA')
    s_22_2_semi_rmt_cap: int | None = Field(default=None, alias='22.2 SEMI RMT CAP')
    s_22_2_semi_rmt_vig: int | None = Field(default=None, alias='22.2 SEMI RMT VIG')
    s_22_2_semi_rmt_eva: int | None = Field(default=None, alias='22.2 SEMI RMT EVA')
    s_23_1_semi_cal_cap: int | None = Field(default=None, alias='23.1 SEMI CAL CAP')
    s_23_1_semi_cal_vig: int | None = Field(default=None, alias='23.1 SEMI CAL VIG')
    s_23_1_semi_cal_eva: int | None = Field(default=None, alias='23.1 SEMI CAL EVA')
    s_23_1_semi_oin_cap: int | None = Field(default=None, alias='23.1 SEMI OIN CAP')
    s_23_1_semi_oin_vig: int | None = Field(default=None, alias='23.1 SEMI OIN VIG')
    s_23_1_semi_oin_eva: int | None = Field(default=None, alias='23.1 SEMI OIN EVA')
    s_23_1_semi_rmt_cap: int | None = Field(default=None, alias='23.1 SEMI RMT CAP')
    s_23_1_semi_rmt_vig: int | None = Field(default=None, alias='23.1 SEMI RMT VIG')
    s_23_1_semi_rmt_eva: int | None = Field(default=None, alias='23.1 SEMI RMT EVA')
    s_23_2_semi_cal_cap: int | None = Field(default=None, alias='23.2 SEMI CAL CAP')
    s_23_2_semi_cal_vig: int | None = Field(default=None, alias='23.2 SEMI CAL VIG')
    s_23_2_semi_cal_eva: int | None = Field(default=None, alias='23.2 SEMI CAL EVA')
    s_23_2_semi_oin_cap: int | None = Field(default=None, alias='23.2 SEMI OIN CAP')
    s_23_2_semi_oin_vig: int | None = Field(default=None, alias='23.2 SEMI OIN VIG')
    s_23_2_semi_oin_eva: int | None = Field(default=None, alias='23.2 SEMI OIN EVA')
    s_23_2_semi_rmt_cap: int | None = Field(default=None, alias='23.2 SEMI RMT CAP')
    s_23_2_semi_rmt_vig: int | None = Field(default=None, alias='23.2 SEMI RMT VIG')
    s_23_2_semi_rmt_eva: int | None = Field(default=None, alias='23.2 SEMI RMT EVA')
    s_24_1_semi_cal_cap: int | None = Field(default=None, alias='24.1 SEMI CAL CAP')
    s_24_1_semi_cal_vig: int | None = Field(default=None, alias='24.1 SEMI CAL VIG')
    s_24_1_semi_cal_eva: int | None = Field(default=None, alias='24.1 SEMI CAL EVA')
    s_24_1_semi_oin_cap: int | None = Field(default=None, alias='24.1 SEMI OIN CAP')
    s_24_1_semi_oin_vig: int | None = Field(default=None, alias='24.1 SEMI OIN VIG')
    s_24_1_semi_oin_eva: int | None = Field(default=None, alias='24.1 SEMI OIN EVA')
    s_24_1_semi_rmt_cap: int | None = Field(default=None, alias='24.1 SEMI RMT CAP')
    s_24_1_semi_rmt_vig: int | None = Field(default=None, alias='24.1 SEMI RMT VIG')
    s_24_1_semi_rmt_eva: int | None = Field(default=None, alias='24.1 SEMI RMT EVA')
    s_24_2_semi_cal_cap: int | None = Field(default=None, alias='24.2 SEMI CAL CAP')
    s_24_2_semi_cal_vig: int | None = Field(default=None, alias='24.2 SEMI CAL VIG')
    s_24_2_semi_cal_eva: int | None = Field(default=None, alias='24.2 SEMI CAL EVA')
    s_24_2_semi_oin_cap: int | None = Field(default=None, alias='24.2 SEMI OIN CAP')
    s_24_2_semi_oin_vig: int | None = Field(default=None, alias='24.2 SEMI OIN VIG')
    s_24_2_semi_oin_eva: int | None = Field(default=None, alias='24.2 SEMI OIN EVA')
    s_24_2_semi_rmt_cap: int | None = Field(default=None, alias='24.2 SEMI RMT CAP')
    s_24_2_semi_rmt_vig: int | None = Field(default=None, alias='24.2 SEMI RMT VIG')
    s_24_2_semi_rmt_eva: int | None = Field(default=None, alias='24.2 SEMI RMT EVA')
    s_25_1_semi_cal_cap: int | None = Field(default=None, alias='25.1 SEMI CAL CAP')
    s_25_1_semi_cal_vig: int | None = Field(default=None, alias='25.1 SEMI CAL VIG')
    s_25_1_semi_cal_eva: int | None = Field(default=None, alias='25.1 SEMI CAL EVA')
    s_25_1_semi_oin_cap: int | None = Field(default=None, alias='25.1 SEMI OIN CAP')
    s_25_1_semi_oin_vig: int | None = Field(default=None, alias='25.1 SEMI OIN VIG')
    s_25_1_semi_oin_eva: int | None = Field(default=None, alias='25.1 SEMI OIN EVA')
    s_25_1_semi_rmt_cap: int | None = Field(default=None, alias='25.1 SEMI RMT CAP')
    s_25_1_semi_rmt_vig: int | None = Field(default=None, alias='25.1 SEMI RMT VIG')
    s_25_1_semi_rmt_eva: int | None = Field(default=None, alias='25.1 SEMI RMT EVA')
    s_25_2_semi_cal_cap: int | None = Field(default=None, alias='25.2 SEMI CAL CAP')
    s_25_2_semi_cal_vig: int | None = Field(default=None, alias='25.2 SEMI CAL VIG')
    s_25_2_semi_cal_eva: int | None = Field(default=None, alias='25.2 SEMI CAL EVA')
    s_25_2_semi_oin_cap: int | None = Field(default=None, alias='25.2 SEMI OIN CAP')
    s_25_2_semi_oin_vig: int | None = Field(default=None, alias='25.2 SEMI OIN VIG')
    s_25_2_semi_oin_eva: int | None = Field(default=None, alias='25.2 SEMI OIN EVA')
    s_25_2_semi_rmt_cap: int | None = Field(default=None, alias='25.2 SEMI RMT CAP')
    s_25_2_semi_rmt_vig: int | None = Field(default=None, alias='25.2 SEMI RMT VIG')
    s_25_2_semi_rmt_eva: int | None = Field(default=None, alias='25.2 SEMI RMT EVA')
    s_26_1_semi_cal_cap: int | None = Field(default=None, alias='26.1 SEMI CAL CAP')
    s_26_1_semi_cal_vig: int | None = Field(default=None, alias='26.1 SEMI CAL VIG')
    s_26_1_semi_cal_eva: int | None = Field(default=None, alias='26.1 SEMI CAL EVA')
    s_26_1_semi_oin_cap: int | None = Field(default=None, alias='26.1 SEMI OIN CAP')
    s_26_1_semi_oin_vig: int | None = Field(default=None, alias='26.1 SEMI OIN VIG')
    s_26_1_semi_oin_eva: int | None = Field(default=None, alias='26.1 SEMI OIN EVA')
    s_26_1_semi_rmt_cap: int | None = Field(default=None, alias='26.1 SEMI RMT CAP')
    s_26_1_semi_rmt_vig: int | None = Field(default=None, alias='26.1 SEMI RMT VIG')
    s_26_1_semi_rmt_eva: int | None = Field(default=None, alias='26.1 SEMI RMT EVA')
    s_26_2_semi_cal_cap: int | None = Field(default=None, alias='26.2 SEMI CAL CAP')
    s_26_2_semi_cal_vig: int | None = Field(default=None, alias='26.2 SEMI CAL VIG')
    s_26_2_semi_cal_eva: int | None = Field(default=None, alias='26.2 SEMI CAL EVA')
    s_26_2_semi_oin_cap: int | None = Field(default=None, alias='26.2 SEMI OIN CAP')
    s_26_2_semi_oin_vig: int | None = Field(default=None, alias='26.2 SEMI OIN VIG')
    s_26_2_semi_oin_eva: int | None = Field(default=None, alias='26.2 SEMI OIN EVA')
    s_26_2_semi_rmt_cap: int | None = Field(default=None, alias='26.2 SEMI RMT CAP')
    s_26_2_semi_rmt_vig: int | None = Field(default=None, alias='26.2 SEMI RMT VIG')
    s_26_2_semi_rmt_eva: int | None = Field(default=None, alias='26.2 SEMI RMT EVA')
    s_27_1_semi_cal_cap: int | None = Field(default=None, alias='27.1 SEMI CAL CAP')
    s_27_1_semi_cal_vig: int | None = Field(default=None, alias='27.1 SEMI CAL VIG')
    s_27_1_semi_cal_eva: int | None = Field(default=None, alias='27.1 SEMI CAL EVA')
    s_27_1_semi_oin_cap: int | None = Field(default=None, alias='27.1 SEMI OIN CAP')
    s_27_1_semi_oin_vig: int | None = Field(default=None, alias='27.1 SEMI OIN VIG')
    s_27_1_semi_oin_eva: int | None = Field(default=None, alias='27.1 SEMI OIN EVA')
    s_27_1_semi_rmt_cap: int | None = Field(default=None, alias='27.1 SEMI RMT CAP')
    s_27_1_semi_rmt_vig: int | None = Field(default=None, alias='27.1 SEMI RMT VIG')
    s_27_1_semi_rmt_eva: int | None = Field(default=None, alias='27.1 SEMI RMT EVA')
    s_27_2_semi_cal_cap: int | None = Field(default=None, alias='27.2 SEMI CAL CAP')
    s_27_2_semi_cal_vig: int | None = Field(default=None, alias='27.2 SEMI CAL VIG')
    s_27_2_semi_cal_eva: int | None = Field(default=None, alias='27.2 SEMI CAL EVA')
    s_27_2_semi_oin_cap: int | None = Field(default=None, alias='27.2 SEMI OIN CAP')
    s_27_2_semi_oin_vig: int | None = Field(default=None, alias='27.2 SEMI OIN VIG')
    s_27_2_semi_oin_eva: int | None = Field(default=None, alias='27.2 SEMI OIN EVA')
    s_27_2_semi_rmt_cap: int | None = Field(default=None, alias='27.2 SEMI RMT CAP')
    s_27_2_semi_rmt_vig: int | None = Field(default=None, alias='27.2 SEMI RMT VIG')
    s_27_2_semi_rmt_eva: int | None = Field(default=None, alias='27.2 SEMI RMT EVA')
    s_28_1_semi_cal_cap: int | None = Field(default=None, alias='28.1 SEMI CAL CAP')
    s_28_1_semi_cal_vig: int | None = Field(default=None, alias='28.1 SEMI CAL VIG')
    s_28_1_semi_cal_eva: int | None = Field(default=None, alias='28.1 SEMI CAL EVA')
    s_28_1_semi_oin_cap: int | None = Field(default=None, alias='28.1 SEMI OIN CAP')
    s_28_1_semi_oin_vig: int | None = Field(default=None, alias='28.1 SEMI OIN VIG')
    s_28_1_semi_oin_eva: int | None = Field(default=None, alias='28.1 SEMI OIN EVA')
    s_28_1_semi_rmt_cap: int | None = Field(default=None, alias='28.1 SEMI RMT CAP')
    s_28_1_semi_rmt_vig: int | None = Field(default=None, alias='28.1 SEMI RMT VIG')
    s_28_1_semi_rmt_eva: int | None = Field(default=None, alias='28.1 SEMI RMT EVA')
    s_28_2_semi_cal_cap: int | None = Field(default=None, alias='28.2 SEMI CAL CAP')
    s_28_2_semi_cal_vig: int | None = Field(default=None, alias='28.2 SEMI CAL VIG')
    s_28_2_semi_cal_eva: int | None = Field(default=None, alias='28.2 SEMI CAL EVA')
    s_28_2_semi_oin_cap: int | None = Field(default=None, alias='28.2 SEMI OIN CAP')
    s_28_2_semi_oin_vig: int | None = Field(default=None, alias='28.2 SEMI OIN VIG')
    s_28_2_semi_oin_eva: int | None = Field(default=None, alias='28.2 SEMI OIN EVA')
    s_28_2_semi_rmt_cap: int | None = Field(default=None, alias='28.2 SEMI RMT CAP')
    s_28_2_semi_rmt_vig: int | None = Field(default=None, alias='28.2 SEMI RMT VIG')
    s_28_2_semi_rmt_eva: int | None = Field(default=None, alias='28.2 SEMI RMT EVA')
    s_29_1_semi_cal_cap: int | None = Field(default=None, alias='29.1 SEMI CAL CAP')
    s_29_1_semi_cal_vig: int | None = Field(default=None, alias='29.1 SEMI CAL VIG')
    s_29_1_semi_cal_eva: int | None = Field(default=None, alias='29.1 SEMI CAL EVA')
    s_29_1_semi_oin_cap: int | None = Field(default=None, alias='29.1 SEMI OIN CAP')
    s_29_1_semi_oin_vig: int | None = Field(default=None, alias='29.1 SEMI OIN VIG')
    s_29_1_semi_oin_eva: int | None = Field(default=None, alias='29.1 SEMI OIN EVA')
    s_29_1_semi_rmt_cap: int | None = Field(default=None, alias='29.1 SEMI RMT CAP')
    s_29_1_semi_rmt_vig: int | None = Field(default=None, alias='29.1 SEMI RMT VIG')
    s_29_1_semi_rmt_eva: int | None = Field(default=None, alias='29.1 SEMI RMT EVA')
    s_29_2_semi_cal_cap: int | None = Field(default=None, alias='29.2 SEMI CAL CAP')
    s_29_2_semi_cal_vig: int | None = Field(default=None, alias='29.2 SEMI CAL VIG')
    s_29_2_semi_cal_eva: int | None = Field(default=None, alias='29.2 SEMI CAL EVA')
    s_29_2_semi_oin_cap: int | None = Field(default=None, alias='29.2 SEMI OIN CAP')
    s_29_2_semi_oin_vig: int | None = Field(default=None, alias='29.2 SEMI OIN VIG')
    s_29_2_semi_oin_eva: int | None = Field(default=None, alias='29.2 SEMI OIN EVA')
    s_29_2_semi_rmt_cap: int | None = Field(default=None, alias='29.2 SEMI RMT CAP')
    s_29_2_semi_rmt_vig: int | None = Field(default=None, alias='29.2 SEMI RMT VIG')
    s_29_2_semi_rmt_eva: int | None = Field(default=None, alias='29.2 SEMI RMT EVA')
    s_30_1_semi_cal_cap: int | None = Field(default=None, alias='30.1 SEMI CAL CAP')
    s_30_1_semi_cal_vig: int | None = Field(default=None, alias='30.1 SEMI CAL VIG')
    s_30_1_semi_cal_eva: int | None = Field(default=None, alias='30.1 SEMI CAL EVA')
    s_30_1_semi_oin_cap: int | None = Field(default=None, alias='30.1 SEMI OIN CAP')
    s_30_1_semi_oin_vig: int | None = Field(default=None, alias='30.1 SEMI OIN VIG')
    s_30_1_semi_oin_eva: int | None = Field(default=None, alias='30.1 SEMI OIN EVA')
    s_30_1_semi_rmt_cap: int | None = Field(default=None, alias='30.1 SEMI RMT CAP')
    s_30_1_semi_rmt_vig: int | None = Field(default=None, alias='30.1 SEMI RMT VIG')
    s_30_1_semi_rmt_eva: int | None = Field(default=None, alias='30.1 SEMI RMT EVA')
    s_30_2_semi_cal_cap: int | None = Field(default=None, alias='30.2 SEMI CAL CAP')
    s_30_2_semi_cal_vig: int | None = Field(default=None, alias='30.2 SEMI CAL VIG')
    s_30_2_semi_cal_eva: int | None = Field(default=None, alias='30.2 SEMI CAL EVA')
    s_30_2_semi_oin_cap: int | None = Field(default=None, alias='30.2 SEMI OIN CAP')
    s_30_2_semi_oin_vig: int | None = Field(default=None, alias='30.2 SEMI OIN VIG')
    s_30_2_semi_oin_eva: int | None = Field(default=None, alias='30.2 SEMI OIN EVA')
    s_30_2_semi_rmt_cap: int | None = Field(default=None, alias='30.2 SEMI RMT CAP')
    s_30_2_semi_rmt_vig: int | None = Field(default=None, alias='30.2 SEMI RMT VIG')
    s_30_2_semi_rmt_eva: int | None = Field(default=None, alias='30.2 SEMI RMT EVA')

    __pydantic_validator__ = field_validator("*", mode='before')(valida_valores_vazios)


class ListaDadosSemi(RootModel):
    root: list[DadosSemi]


class DadosEadc(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    dias: int | None = Field(default=None, alias='Dias')
    s_18_2_eadc_cal_cap: int | None = Field(default=None, alias='18.2 EADC CAL CAP')
    s_18_2_eadc_cal_vig: int | None = Field(default=None, alias='18.2 EADC CAL VIG')
    s_18_2_eadc_cal_eva: int | None = Field(default=None, alias='18.2 EADC CAL EVA')
    s_18_2_eadc_oin_cap: int | None = Field(default=None, alias='18.2 EADC OIN CAP')
    s_18_2_eadc_oin_vig: int | None = Field(default=None, alias='18.2 EADC OIN VIG')
    s_18_2_eadc_oin_eva: int | None = Field(default=None, alias='18.2 EADC OIN EVA')
    s_18_2_eadc_rmt_cap: int | None = Field(default=None, alias='18.2 EADC REM CAP')
    s_18_2_eadc_rmt_vig: int | None = Field(default=None, alias='18.2 EADC REM VIG')
    s_18_2_eadc_rmt_eva: int | None = Field(default=None, alias='18.2 EADC RMT EVA')
    s_19_1_eadc_cal_cap: int | None = Field(default=None, alias='19.1 EADC CAL CAP')
    s_19_1_eadc_cal_vig: int | None = Field(default=None, alias='19.1 EADC CAL VIG')
    s_19_1_eadc_cal_eva: int | None = Field(default=None, alias='19.1 EADC CAL EVA')
    s_19_1_eadc_oin_cap: int | None = Field(default=None, alias='19.1 EADC OIN CAP')
    s_19_1_eadc_oin_vig: int | None = Field(default=None, alias='19.1 EADC OIN VIG')
    s_19_1_eadc_oin_eva: int | None = Field(default=None, alias='19.1 EADC OIN EVA')
    s_19_1_eadc_rmt_cap: int | None = Field(default=None, alias='19.1 EADC REM CAP')
    s_19_1_eadc_rmt_vig: int | None = Field(default=None, alias='19.1 EADC REM VIG')
    s_19_1_eadc_rmt_eva: int | None = Field(default=None, alias='19.1 EADC RMT EVA')
    s_19_2_eadc_cal_cap: int | None = Field(default=None, alias='19.2 EADC CAL CAP')
    s_19_2_eadc_cal_vig: int | None = Field(default=None, alias='19.2 EADC CAL VIG')
    s_19_2_eadc_cal_eva: int | None = Field(default=None, alias='19.2 EADC CAL EVA')
    s_19_2_eadc_oin_cap: int | None = Field(default=None, alias='19.2 EADC OIN CAP')
    s_19_2_eadc_oin_vig: int | None = Field(default=None, alias='19.2 EADC OIN VIG')
    s_19_2_eadc_oin_eva: int | None = Field(default=None, alias='19.2 EADC OIN EVA')
    s_19_2_eadc_rmt_cap: int | None = Field(default=None, alias='19.2 EADC REM CAP')
    s_19_2_eadc_rmt_vig: int | None = Field(default=None, alias='19.2 EADC REM VIG')
    s_19_2_eadc_rmt_eva: int | None = Field(default=None, alias='19.2 EADC RMT EVA')
    s_20_1_eadc_cal_cap: int | None = Field(default=None, alias='20.1 EADC CAL CAP')
    s_20_1_eadc_cal_vig: int | None = Field(default=None, alias='20.1 EADC CAL VIG')
    s_20_1_eadc_cal_eva: int | None = Field(default=None, alias='20.1 EADC CAL EVA')
    s_20_1_eadc_oin_cap: int | None = Field(default=None, alias='20.1 EADC OIN CAP')
    s_20_1_eadc_oin_vig: int | None = Field(default=None, alias='20.1 EADC OIN VIG')
    s_20_1_eadc_oin_eva: int | None = Field(default=None, alias='20.1 EADC OIN EVA')
    s_20_1_eadc_rmt_cap: int | None = Field(default=None, alias='20.1 EADC REM CAP')
    s_20_1_eadc_rmt_vig: int | None = Field(default=None, alias='20.1 EADC REM VIG')
    s_20_1_eadc_rmt_eva: int | None = Field(default=None, alias='20.1 EADC RMT EVA')
    s_20_2_eadc_cal_cap: int | None = Field(default=None, alias='20.2 EADC CAL CAP')
    s_20_2_eadc_cal_vig: int | None = Field(default=None, alias='20.2 EADC CAL VIG')
    s_20_2_eadc_cal_eva: int | None = Field(default=None, alias='20.2 EADC CAL EVA')
    s_20_2_eadc_oin_cap: int | None = Field(default=None, alias='20.2 EADC OIN CAP')
    s_20_2_eadc_oin_vig: int | None = Field(default=None, alias='20.2 EADC OIN VIG')
    s_20_2_eadc_oin_eva: int | None = Field(default=None, alias='20.2 EADC OIN EVA')
    s_20_2_eadc_rmt_cap: int | None = Field(default=None, alias='20.2 EADC REM CAP')
    s_20_2_eadc_rmt_vig: int | None = Field(default=None, alias='20.2 EADC REM VIG')
    s_20_2_eadc_rmt_eva: int | None = Field(default=None, alias='20.2 EADC RMT EVA')
    s_21_1_eadc_cal_cap: int | None = Field(default=None, alias='21.1 EADC CAL CAP')
    s_21_1_eadc_cal_vig: int | None = Field(default=None, alias='21.1 EADC CAL VIG')
    s_21_1_eadc_cal_eva: int | None = Field(default=None, alias='21.1 EADC CAL EVA')
    s_21_1_eadc_oin_cap: int | None = Field(default=None, alias='21.1 EADC OIN CAP')
    s_21_1_eadc_oin_vig: int | None = Field(default=None, alias='21.1 EADC OIN VIG')
    s_21_1_eadc_oin_eva: int | None = Field(default=None, alias='21.1 EADC OIN EVA')
    s_21_1_eadc_rmt_cap: int | None = Field(default=None, alias='21.1 EADC REM CAP')
    s_21_1_eadc_rmt_vig: int | None = Field(default=None, alias='21.1 EADC REM VIG')
    s_21_1_eadc_rmt_eva: int | None = Field(default=None, alias='21.1 EADC RMT EVA')
    s_21_2_eadc_cal_cap: int | None = Field(default=None, alias='21.2 EADC CAL CAP')
    s_21_2_eadc_cal_vig: int | None = Field(default=None, alias='21.2 EADC CAL VIG')
    s_21_2_eadc_cal_eva: int | None = Field(default=None, alias='21.2 EADC CAL EVA')
    s_21_2_eadc_oin_cap: int | None = Field(default=None, alias='21.2 EADC OIN CAP')
    s_21_2_eadc_oin_vig: int | None = Field(default=None, alias='21.2 EADC OIN VIG')
    s_21_2_eadc_oin_eva: int | None = Field(default=None, alias='21.2 EADC OIN EVA')
    s_21_2_eadc_rmt_cap: int | None = Field(default=None, alias='21.2 EADC REM CAP')
    s_21_2_eadc_rmt_vig: int | None = Field(default=None, alias='21.2 EADC REM VIG')
    s_21_2_eadc_rmt_eva: int | None = Field(default=None, alias='21.2 EADC RMT EVA')
    s_22_1_eadc_cal_cap: int | None = Field(default=None, alias='22.1 EADC CAL CAP')
    s_22_1_eadc_cal_vig: int | None = Field(default=None, alias='22.1 EADC CAL VIG')
    s_22_1_eadc_cal_eva: int | None = Field(default=None, alias='22.1 EADC CAL EVA')
    s_22_1_eadc_oin_cap: int | None = Field(default=None, alias='22.1 EADC OIN CAP')
    s_22_1_eadc_oin_vig: int | None = Field(default=None, alias='22.1 EADC OIN VIG')
    s_22_1_eadc_oin_eva: int | None = Field(default=None, alias='22.1 EADC OIN EVA')
    s_22_1_eadc_rmt_cap: int | None = Field(default=None, alias='22.1 EADC REM CAP')
    s_22_1_eadc_rmt_vig: int | None = Field(default=None, alias='22.1 EADC REM VIG')
    s_22_1_eadc_rmt_eva: int | None = Field(default=None, alias='22.1 EADC RMT EVA')
    s_22_2_eadc_cal_cap: int | None = Field(default=None, alias='22.2 EADC CAL CAP')
    s_22_2_eadc_cal_vig: int | None = Field(default=None, alias='22.2 EADC CAL VIG')
    s_22_2_eadc_cal_eva: int | None = Field(default=None, alias='22.2 EADC CAL EVA')
    s_22_2_eadc_oin_cap: int | None = Field(default=None, alias='22.2 EADC OIN CAP')
    s_22_2_eadc_oin_vig: int | None = Field(default=None, alias='22.2 EADC OIN VIG')
    s_22_2_eadc_oin_eva: int | None = Field(default=None, alias='22.2 EADC OIN EVA')
    s_22_2_eadc_rmt_cap: int | None = Field(default=None, alias='22.2 EADC REM CAP')
    s_22_2_eadc_rmt_vig: int | None = Field(default=None, alias='22.2 EADC REM VIG')
    s_22_2_eadc_rmt_eva: int | None = Field(default=None, alias='22.2 EADC RMT EVA')
    s_23_1_eadc_cal_cap: int | None = Field(default=None, alias='23.1 EADC CAL CAP')
    s_23_1_eadc_cal_vig: int | None = Field(default=None, alias='23.1 EADC CAL VIG')
    s_23_1_eadc_cal_eva: int | None = Field(default=None, alias='23.1 EADC CAL EVA')
    s_23_1_eadc_oin_cap: int | None = Field(default=None, alias='23.1 EADC OIN CAP')
    s_23_1_eadc_oin_vig: int | None = Field(default=None, alias='23.1 EADC OIN VIG')
    s_23_1_eadc_oin_eva: int | None = Field(default=None, alias='23.1 EADC OIN EVA')
    s_23_1_eadc_rmt_cap: int | None = Field(default=None, alias='23.1 EADC REM CAP')
    s_23_1_eadc_rmt_vig: int | None = Field(default=None, alias='23.1 EADC REM VIG')
    s_23_1_eadc_rmt_eva: int | None = Field(default=None, alias='23.1 EADC RMT EVA')
    s_23_2_eadc_cal_cap: int | None = Field(default=None, alias='23.2 EADC CAL CAP')
    s_23_2_eadc_cal_vig: int | None = Field(default=None, alias='23.2 EADC CAL VIG')
    s_23_2_eadc_cal_eva: int | None = Field(default=None, alias='23.2 EADC CAL EVA')
    s_23_2_eadc_oin_cap: int | None = Field(default=None, alias='23.2 EADC OIN CAP')
    s_23_2_eadc_oin_vig: int | None = Field(default=None, alias='23.2 EADC OIN VIG')
    s_23_2_eadc_oin_eva: int | None = Field(default=None, alias='23.2 EADC OIN EVA')
    s_23_2_eadc_rmt_cap: int | None = Field(default=None, alias='23.2 EADC REM CAP')
    s_23_2_eadc_rmt_vig: int | None = Field(default=None, alias='23.2 EADC REM VIG')
    s_23_2_eadc_rmt_eva: int | None = Field(default=None, alias='23.2 EADC RMT EVA')
    s_24_1_eadc_cal_cap: int | None = Field(default=None, alias='24.1 EADC CAL CAP')
    s_24_1_eadc_cal_vig: int | None = Field(default=None, alias='24.1 EADC CAL VIG')
    s_24_1_eadc_cal_eva: int | None = Field(default=None, alias='24.1 EADC CAL EVA')
    s_24_1_eadc_oin_cap: int | None = Field(default=None, alias='24.1 EADC OIN CAP')
    s_24_1_eadc_oin_vig: int | None = Field(default=None, alias='24.1 EADC OIN VIG')
    s_24_1_eadc_oin_eva: int | None = Field(default=None, alias='24.1 EADC OIN EVA')
    s_24_1_eadc_rmt_cap: int | None = Field(default=None, alias='24.1 EADC REM CAP')
    s_24_1_eadc_rmt_vig: int | None = Field(default=None, alias='24.1 EADC REM VIG')
    s_24_1_eadc_rmt_eva: int | None = Field(default=None, alias='24.1 EADC RMT EVA')
    s_24_2_eadc_cal_cap: int | None = Field(default=None, alias='24.2 EADC CAL CAP')
    s_24_2_eadc_cal_vig: int | None = Field(default=None, alias='24.2 EADC CAL VIG')
    s_24_2_eadc_cal_eva: int | None = Field(default=None, alias='24.2 EADC CAL EVA')
    s_24_2_eadc_oin_cap: int | None = Field(default=None, alias='24.2 EADC OIN CAP')
    s_24_2_eadc_oin_vig: int | None = Field(default=None, alias='24.2 EADC OIN VIG')
    s_24_2_eadc_oin_eva: int | None = Field(default=None, alias='24.2 EADC OIN EVA')
    s_24_2_eadc_rmt_cap: int | None = Field(default=None, alias='24.2 EADC REM CAP')
    s_24_2_eadc_rmt_vig: int | None = Field(default=None, alias='24.2 EADC REM VIG')
    s_24_2_eadc_rmt_eva: int | None = Field(default=None, alias='24.2 EADC RMT EVA')
    s_25_1_eadc_cal_cap: int | None = Field(default=None, alias='25.1 EADC CAL CAP')
    s_25_1_eadc_cal_vig: int | None = Field(default=None, alias='25.1 EADC CAL VIG')
    s_25_1_eadc_cal_eva: int | None = Field(default=None, alias='25.1 EADC CAL EVA')
    s_25_1_eadc_oin_cap: int | None = Field(default=None, alias='25.1 EADC OIN CAP')
    s_25_1_eadc_oin_vig: int | None = Field(default=None, alias='25.1 EADC OIN VIG')
    s_25_1_eadc_oin_eva: int | None = Field(default=None, alias='25.1 EADC OIN EVA')
    s_25_1_eadc_rmt_cap: int | None = Field(default=None, alias='25.1 EADC REM CAP')
    s_25_1_eadc_rmt_vig: int | None = Field(default=None, alias='25.1 EADC REM VIG')
    s_25_1_eadc_rmt_eva: int | None = Field(default=None, alias='25.1 EADC RMT EVA')
    s_25_2_eadc_cal_cap: int | None = Field(default=None, alias='25.2 EADC CAL CAP')
    s_25_2_eadc_cal_vig: int | None = Field(default=None, alias='25.2 EADC CAL VIG')
    s_25_2_eadc_cal_eva: int | None = Field(default=None, alias='25.2 EADC CAL EVA')
    s_25_2_eadc_oin_cap: int | None = Field(default=None, alias='25.2 EADC OIN CAP')
    s_25_2_eadc_oin_vig: int | None = Field(default=None, alias='25.2 EADC OIN VIG')
    s_25_2_eadc_oin_eva: int | None = Field(default=None, alias='25.2 EADC OIN EVA')
    s_25_2_eadc_rmt_cap: int | None = Field(default=None, alias='25.2 EADC REM CAP')
    s_25_2_eadc_rmt_vig: int | None = Field(default=None, alias='25.2 EADC REM VIG')
    s_25_2_eadc_rmt_eva: int | None = Field(default=None, alias='25.2 EADC RMT EVA')
    s_26_1_eadc_cal_cap: int | None = Field(default=None, alias='26.1 EADC CAL CAP')
    s_26_1_eadc_cal_vig: int | None = Field(default=None, alias='26.1 EADC CAL VIG')
    s_26_1_eadc_cal_eva: int | None = Field(default=None, alias='26.1 EADC CAL EVA')
    s_26_1_eadc_oin_cap: int | None = Field(default=None, alias='26.1 EADC OIN CAP')
    s_26_1_eadc_oin_vig: int | None = Field(default=None, alias='26.1 EADC OIN VIG')
    s_26_1_eadc_oin_eva: int | None = Field(default=None, alias='26.1 EADC OIN EVA')
    s_26_1_eadc_rmt_cap: int | None = Field(default=None, alias='26.1 EADC REM CAP')
    s_26_1_eadc_rmt_vig: int | None = Field(default=None, alias='26.1 EADC REM VIG')
    s_26_1_eadc_rmt_eva: int | None = Field(default=None, alias='26.1 EADC RMT EVA')
    s_26_2_eadc_cal_cap: int | None = Field(default=None, alias='26.2 EADC CAL CAP')
    s_26_2_eadc_cal_vig: int | None = Field(default=None, alias='26.2 EADC CAL VIG')
    s_26_2_eadc_cal_eva: int | None = Field(default=None, alias='26.2 EADC CAL EVA')
    s_26_2_eadc_oin_cap: int | None = Field(default=None, alias='26.2 EADC OIN CAP')
    s_26_2_eadc_oin_vig: int | None = Field(default=None, alias='26.2 EADC OIN VIG')
    s_26_2_eadc_oin_eva: int | None = Field(default=None, alias='26.2 EADC OIN EVA')
    s_26_2_eadc_rmt_cap: int | None = Field(default=None, alias='26.2 EADC REM CAP')
    s_26_2_eadc_rmt_vig: int | None = Field(default=None, alias='26.2 EADC REM VIG')
    s_26_2_eadc_rmt_eva: int | None = Field(default=None, alias='26.2 EADC RMT EVA')
    s_27_1_eadc_cal_cap: int | None = Field(default=None, alias='27.1 EADC CAL CAP')
    s_27_1_eadc_cal_vig: int | None = Field(default=None, alias='27.1 EADC CAL VIG')
    s_27_1_eadc_cal_eva: int | None = Field(default=None, alias='27.1 EADC CAL EVA')
    s_27_1_eadc_oin_cap: int | None = Field(default=None, alias='27.1 EADC OIN CAP')
    s_27_1_eadc_oin_vig: int | None = Field(default=None, alias='27.1 EADC OIN VIG')
    s_27_1_eadc_oin_eva: int | None = Field(default=None, alias='27.1 EADC OIN EVA')
    s_27_1_eadc_rmt_cap: int | None = Field(default=None, alias='27.1 EADC REM CAP')
    s_27_1_eadc_rmt_vig: int | None = Field(default=None, alias='27.1 EADC REM VIG')
    s_27_1_eadc_rmt_eva: int | None = Field(default=None, alias='27.1 EADC RMT EVA')
    s_27_2_eadc_cal_cap: int | None = Field(default=None, alias='27.2 EADC CAL CAP')
    s_27_2_eadc_cal_vig: int | None = Field(default=None, alias='27.2 EADC CAL VIG')
    s_27_2_eadc_cal_eva: int | None = Field(default=None, alias='27.2 EADC CAL EVA')
    s_27_2_eadc_oin_cap: int | None = Field(default=None, alias='27.2 EADC OIN CAP')
    s_27_2_eadc_oin_vig: int | None = Field(default=None, alias='27.2 EADC OIN VIG')
    s_27_2_eadc_oin_eva: int | None = Field(default=None, alias='27.2 EADC OIN EVA')
    s_27_2_eadc_rmt_cap: int | None = Field(default=None, alias='27.2 EADC REM CAP')
    s_27_2_eadc_rmt_vig: int | None = Field(default=None, alias='27.2 EADC REM VIG')
    s_27_2_eadc_rmt_eva: int | None = Field(default=None, alias='27.2 EADC RMT EVA')
    s_28_1_eadc_cal_cap: int | None = Field(default=None, alias='28.1 EADC CAL CAP')
    s_28_1_eadc_cal_vig: int | None = Field(default=None, alias='28.1 EADC CAL VIG')
    s_28_1_eadc_cal_eva: int | None = Field(default=None, alias='28.1 EADC CAL EVA')
    s_28_1_eadc_oin_cap: int | None = Field(default=None, alias='28.1 EADC OIN CAP')
    s_28_1_eadc_oin_vig: int | None = Field(default=None, alias='28.1 EADC OIN VIG')
    s_28_1_eadc_oin_eva: int | None = Field(default=None, alias='28.1 EADC OIN EVA')
    s_28_1_eadc_rmt_cap: int | None = Field(default=None, alias='28.1 EADC REM CAP')
    s_28_1_eadc_rmt_vig: int | None = Field(default=None, alias='28.1 EADC REM VIG')
    s_28_1_eadc_rmt_eva: int | None = Field(default=None, alias='28.1 EADC RMT EVA')
    s_28_2_eadc_cal_cap: int | None = Field(default=None, alias='28.2 EADC CAL CAP')
    s_28_2_eadc_cal_vig: int | None = Field(default=None, alias='28.2 EADC CAL VIG')
    s_28_2_eadc_cal_eva: int | None = Field(default=None, alias='28.2 EADC CAL EVA')
    s_28_2_eadc_oin_cap: int | None = Field(default=None, alias='28.2 EADC OIN CAP')
    s_28_2_eadc_oin_vig: int | None = Field(default=None, alias='28.2 EADC OIN VIG')
    s_28_2_eadc_oin_eva: int | None = Field(default=None, alias='28.2 EADC OIN EVA')
    s_28_2_eadc_rmt_cap: int | None = Field(default=None, alias='28.2 EADC REM CAP')
    s_28_2_eadc_rmt_vig: int | None = Field(default=None, alias='28.2 EADC REM VIG')
    s_28_2_eadc_rmt_eva: int | None = Field(default=None, alias='28.2 EADC RMT EVA')
    s_29_1_eadc_cal_cap: int | None = Field(default=None, alias='29.1 EADC CAL CAP')
    s_29_1_eadc_cal_vig: int | None = Field(default=None, alias='29.1 EADC CAL VIG')
    s_29_1_eadc_cal_eva: int | None = Field(default=None, alias='29.1 EADC CAL EVA')
    s_29_1_eadc_oin_cap: int | None = Field(default=None, alias='29.1 EADC OIN CAP')
    s_29_1_eadc_oin_vig: int | None = Field(default=None, alias='29.1 EADC OIN VIG')
    s_29_1_eadc_oin_eva: int | None = Field(default=None, alias='29.1 EADC OIN EVA')
    s_29_1_eadc_rmt_cap: int | None = Field(default=None, alias='29.1 EADC REM CAP')
    s_29_1_eadc_rmt_vig: int | None = Field(default=None, alias='29.1 EADC REM VIG')
    s_29_1_eadc_rmt_eva: int | None = Field(default=None, alias='29.1 EADC RMT EVA')
    s_29_2_eadc_cal_cap: int | None = Field(default=None, alias='29.2 EADC CAL CAP')
    s_29_2_eadc_cal_vig: int | None = Field(default=None, alias='29.2 EADC CAL VIG')
    s_29_2_eadc_cal_eva: int | None = Field(default=None, alias='29.2 EADC CAL EVA')
    s_29_2_eadc_oin_cap: int | None = Field(default=None, alias='29.2 EADC OIN CAP')
    s_29_2_eadc_oin_vig: int | None = Field(default=None, alias='29.2 EADC OIN VIG')
    s_29_2_eadc_oin_eva: int | None = Field(default=None, alias='29.2 EADC OIN EVA')
    s_29_2_eadc_rmt_cap: int | None = Field(default=None, alias='29.2 EADC REM CAP')
    s_29_2_eadc_rmt_vig: int | None = Field(default=None, alias='29.2 EADC REM VIG')
    s_29_2_eadc_rmt_eva: int | None = Field(default=None, alias='29.2 EADC RMT EVA')
    s_30_1_eadc_cal_cap: int | None = Field(default=None, alias='30.1 EADC CAL CAP')
    s_30_1_eadc_cal_vig: int | None = Field(default=None, alias='30.1 EADC CAL VIG')
    s_30_1_eadc_cal_eva: int | None = Field(default=None, alias='30.1 EADC CAL EVA')
    s_30_1_eadc_oin_cap: int | None = Field(default=None, alias='30.1 EADC OIN CAP')
    s_30_1_eadc_oin_vig: int | None = Field(default=None, alias='30.1 EADC OIN VIG')
    s_30_1_eadc_oin_eva: int | None = Field(default=None, alias='30.1 EADC OIN EVA')
    s_30_1_eadc_rmt_cap: int | None = Field(default=None, alias='30.1 EADC REM CAP')
    s_30_1_eadc_rmt_vig: int | None = Field(default=None, alias='30.1 EADC REM VIG')
    s_30_1_eadc_rmt_eva: int | None = Field(default=None, alias='30.1 EADC RMT EVA')
    s_30_2_eadc_cal_cap: int | None = Field(default=None, alias='30.2 EADC CAL CAP')
    s_30_2_eadc_cal_vig: int | None = Field(default=None, alias='30.2 EADC CAL VIG')
    s_30_2_eadc_cal_eva: int | None = Field(default=None, alias='30.2 EADC CAL EVA')
    s_30_2_eadc_oin_cap: int | None = Field(default=None, alias='30.2 EADC OIN CAP')
    s_30_2_eadc_oin_vig: int | None = Field(default=None, alias='30.2 EADC OIN VIG')
    s_30_2_eadc_oin_eva: int | None = Field(default=None, alias='30.2 EADC OIN EVA')
    s_30_2_eadc_rmt_cap: int | None = Field(default=None, alias='30.2 EADC REM CAP')
    s_30_2_eadc_rmt_vig: int | None = Field(default=None, alias='30.2 EADC REM VIG')
    s_30_2_eadc_rmt_eva: int | None = Field(default=None, alias='30.2 EADC RMT EVA')

    __pydantic_validator__ = field_validator("*", mode='before')(valida_valores_vazios)


class DadosPres(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    dias: int | None = Field(default=None, alias='Dias')
    s_18_2_pres_cal_cap: int | None = Field(default=None, alias='18.2 PRES CAL CAP')
    s_18_2_pres_cal_vig: int | None = Field(default=None, alias='18.2 PRES CAL VIG')
    s_18_2_pres_cal_eva: int | None = Field(default=None, alias='18.2 PRES CAL EVA')
    s_18_2_pres_oin_cap: int | None = Field(default=None, alias='18.2 PRES OIN CAP')
    s_18_2_pres_oin_vig: int | None = Field(default=None, alias='18.2 PRES OIN VIG')
    s_18_2_pres_oin_eva: int | None = Field(default=None, alias='18.2 PRES OIN EVA')
    s_18_2_pres_rmt_cap: int | None = Field(default=None, alias='18.2 PRES RMT CAP')
    s_18_2_pres_rmt_vig: int | None = Field(default=None, alias='18.2 PRES RMT VIG')
    s_18_2_pres_rmt_eva: int | None = Field(default=None, alias='18.2 PRES RMT EVA')
    s_19_1_pres_cal_cap: int | None = Field(default=None, alias='19.1 PRES CAL CAP')
    s_19_1_pres_cal_vig: int | None = Field(default=None, alias='19.1 PRES CAL VIG')
    s_19_1_pres_cal_eva: int | None = Field(default=None, alias='19.1 PRES CAL EVA')
    s_19_1_pres_oin_cap: int | None = Field(default=None, alias='19.1 PRES OIN CAP')
    s_19_1_pres_oin_vig: int | None = Field(default=None, alias='19.1 PRES OIN VIG')
    s_19_1_pres_oin_eva: int | None = Field(default=None, alias='19.1 PRES OIN EVA')
    s_19_1_pres_rmt_cap: int | None = Field(default=None, alias='19.1 PRES RMT CAP')
    s_19_1_pres_rmt_vig: int | None = Field(default=None, alias='19.1 PRES RMT VIG')
    s_19_1_pres_rmt_eva: int | None = Field(default=None, alias='19.1 PRES RMT EVA')
    s_19_2_pres_cal_cap: int | None = Field(default=None, alias='19.2 PRES CAL CAP')
    s_19_2_pres_cal_vig: int | None = Field(default=None, alias='19.2 PRES CAL VIG')
    s_19_2_pres_cal_eva: int | None = Field(default=None, alias='19.2 PRES CAL EVA')
    s_19_2_pres_oin_cap: int | None = Field(default=None, alias='19.2 PRES OIN CAP')
    s_19_2_pres_oin_vig: int | None = Field(default=None, alias='19.2 PRES OIN VIG')
    s_19_2_pres_oin_eva: int | None = Field(default=None, alias='19.2 PRES OIN EVA')
    s_19_2_pres_rmt_cap: int | None = Field(default=None, alias='19.2 PRES RMT CAP')
    s_19_2_pres_rmt_vig: int | None = Field(default=None, alias='19.2 PRES RMT VIG')
    s_19_2_pres_rmt_eva: int | None = Field(default=None, alias='19.2 PRES RMT EVA')
    s_20_1_pres_cal_cap: int | None = Field(default=None, alias='20.1 PRES CAL CAP')
    s_20_1_pres_cal_vig: int | None = Field(default=None, alias='20.1 PRES CAL VIG')
    s_20_1_pres_cal_eva: int | None = Field(default=None, alias='20.1 PRES CAL EVA')
    s_20_1_pres_oin_cap: int | None = Field(default=None, alias='20.1 PRES OIN CAP')
    s_20_1_pres_oin_vig: int | None = Field(default=None, alias='20.1 PRES OIN VIG')
    s_20_1_pres_oin_eva: int | None = Field(default=None, alias='20.1 PRES OIN EVA')
    s_20_1_pres_rmt_cap: int | None = Field(default=None, alias='20.1 PRES RMT CAP')
    s_20_1_pres_rmt_vig: int | None = Field(default=None, alias='20.1 PRES RMT VIG')
    s_20_1_pres_rmt_eva: int | None = Field(default=None, alias='20.1 PRES RMT EVA')
    s_20_2_pres_cal_cap: int | None = Field(default=None, alias='20.2 PRES CAL CAP')
    s_20_2_pres_cal_vig: int | None = Field(default=None, alias='20.2 PRES CAL VIG')
    s_20_2_pres_cal_eva: int | None = Field(default=None, alias='20.2 PRES CAL EVA')
    s_20_2_pres_oin_cap: int | None = Field(default=None, alias='20.2 PRES OIN CAP')
    s_20_2_pres_oin_vig: int | None = Field(default=None, alias='20.2 PRES OIN VIG')
    s_20_2_pres_oin_eva: int | None = Field(default=None, alias='20.2 PRES OIN EVA')
    s_20_2_pres_rmt_cap: int | None = Field(default=None, alias='20.2 PRES RMT CAP')
    s_20_2_pres_rmt_vig: int | None = Field(default=None, alias='20.2 PRES RMT VIG')
    s_20_2_pres_rmt_eva: int | None = Field(default=None, alias='20.2 PRES RMT EVA')
    s_21_1_pres_cal_cap: int | None = Field(default=None, alias='21.1 PRES CAL CAP')
    s_21_1_pres_cal_vig: int | None = Field(default=None, alias='21.1 PRES CAL VIG')
    s_21_1_pres_cal_eva: int | None = Field(default=None, alias='21.1 PRES CAL EVA')
    s_21_1_pres_oin_cap: int | None = Field(default=None, alias='21.1 PRES OIN CAP')
    s_21_1_pres_oin_vig: int | None = Field(default=None, alias='21.1 PRES OIN VIG')
    s_21_1_pres_oin_eva: int | None = Field(default=None, alias='21.1 PRES OIN EVA')
    s_21_1_pres_rmt_cap: int | None = Field(default=None, alias='21.1 PRES RMT CAP')
    s_21_1_pres_rmt_vig: int | None = Field(default=None, alias='21.1 PRES RMT VIG')
    s_21_1_pres_rmt_eva: int | None = Field(default=None, alias='21.1 PRES RMT EVA')
    s_21_2_pres_cal_cap: int | None = Field(default=None, alias='21.2 PRES CAL CAP')
    s_21_2_pres_cal_vig: int | None = Field(default=None, alias='21.2 PRES CAL VIG')
    s_21_2_pres_cal_eva: int | None = Field(default=None, alias='21.2 PRES CAL EVA')
    s_21_2_pres_oin_cap: int | None = Field(default=None, alias='21.2 PRES OIN CAP')
    s_21_2_pres_oin_vig: int | None = Field(default=None, alias='21.2 PRES OIN VIG')
    s_21_2_pres_oin_eva: int | None = Field(default=None, alias='21.2 PRES OIN EVA')
    s_21_2_pres_rmt_cap: int | None = Field(default=None, alias='21.2 PRES RMT CAP')
    s_21_2_pres_rmt_vig: int | None = Field(default=None, alias='21.2 PRES RMT VIG')
    s_21_2_pres_rmt_eva: int | None = Field(default=None, alias='21.2 PRES RMT EVA')
    s_22_1_pres_cal_cap: int | None = Field(default=None, alias='22.1 PRES CAL CAP')
    s_22_1_pres_cal_vig: int | None = Field(default=None, alias='22.1 PRES CAL VIG')
    s_22_1_pres_cal_eva: int | None = Field(default=None, alias='22.1 PRES CAL EVA')
    s_22_1_pres_oin_cap: int | None = Field(default=None, alias='22.1 PRES OIN CAP')
    s_22_1_pres_oin_vig: int | None = Field(default=None, alias='22.1 PRES OIN VIG')
    s_22_1_pres_oin_eva: int | None = Field(default=None, alias='22.1 PRES OIN EVA')
    s_22_1_pres_rmt_cap: int | None = Field(default=None, alias='22.1 PRES RMT CAP')
    s_22_1_pres_rmt_vig: int | None = Field(default=None, alias='22.1 PRES RMT VIG')
    s_22_1_pres_rmt_eva: int | None = Field(default=None, alias='22.1 PRES RMT EVA')
    s_22_2_pres_cal_cap: int | None = Field(default=None, alias='22.2 PRES CAL CAP')
    s_22_2_pres_cal_vig: int | None = Field(default=None, alias='22.2 PRES CAL VIG')
    s_22_2_pres_cal_eva: int | None = Field(default=None, alias='22.2 PRES CAL EVA')
    s_22_2_pres_oin_cap: int | None = Field(default=None, alias='22.2 PRES OIN CAP')
    s_22_2_pres_oin_vig: int | None = Field(default=None, alias='22.2 PRES OIN VIG')
    s_22_2_pres_oin_eva: int | None = Field(default=None, alias='22.2 PRES OIN EVA')
    s_22_2_pres_rmt_cap: int | None = Field(default=None, alias='22.2 PRES RMT CAP')
    s_22_2_pres_rmt_vig: int | None = Field(default=None, alias='22.2 PRES RMT VIG')
    s_22_2_pres_rmt_eva: int | None = Field(default=None, alias='22.2 PRES RMT EVA')
    s_23_1_pres_cal_cap: int | None = Field(default=None, alias='23.1 PRES CAL CAP')
    s_23_1_pres_cal_vig: int | None = Field(default=None, alias='23.1 PRES CAL VIG')
    s_23_1_pres_cal_eva: int | None = Field(default=None, alias='23.1 PRES CAL EVA')
    s_23_1_pres_oin_cap: int | None = Field(default=None, alias='23.1 PRES OIN CAP')
    s_23_1_pres_oin_vig: int | None = Field(default=None, alias='23.1 PRES OIN VIG')
    s_23_1_pres_oin_eva: int | None = Field(default=None, alias='23.1 PRES OIN EVA')
    s_23_1_pres_rmt_cap: int | None = Field(default=None, alias='23.1 PRES RMT CAP')
    s_23_1_pres_rmt_vig: int | None = Field(default=None, alias='23.1 PRES RMT VIG')
    s_23_1_pres_rmt_eva: int | None = Field(default=None, alias='23.1 PRES RMT EVA')
    s_23_2_pres_cal_cap: int | None = Field(default=None, alias='23.2 PRES CAL CAP')
    s_23_2_pres_cal_vig: int | None = Field(default=None, alias='23.2 PRES CAL VIG')
    s_23_2_pres_cal_eva: int | None = Field(default=None, alias='23.2 PRES CAL EVA')
    s_23_2_pres_oin_cap: int | None = Field(default=None, alias='23.2 PRES OIN CAP')
    s_23_2_pres_oin_vig: int | None = Field(default=None, alias='23.2 PRES OIN VIG')
    s_23_2_pres_oin_eva: int | None = Field(default=None, alias='23.2 PRES OIN EVA')
    s_23_2_pres_rmt_cap: int | None = Field(default=None, alias='23.2 PRES RMT CAP')
    s_23_2_pres_rmt_vig: int | None = Field(default=None, alias='23.2 PRES RMT VIG')
    s_23_2_pres_rmt_eva: int | None = Field(default=None, alias='23.2 PRES RMT EVA')
    s_24_1_pres_cal_cap: int | None = Field(default=None, alias='24.1 PRES CAL CAP')
    s_24_1_pres_cal_vig: int | None = Field(default=None, alias='24.1 PRES CAL VIG')
    s_24_1_pres_cal_eva: int | None = Field(default=None, alias='24.1 PRES CAL EVA')
    s_24_1_pres_oin_cap: int | None = Field(default=None, alias='24.1 PRES OIN CAP')
    s_24_1_pres_oin_vig: int | None = Field(default=None, alias='24.1 PRES OIN VIG')
    s_24_1_pres_oin_eva: int | None = Field(default=None, alias='24.1 PRES OIN EVA')
    s_24_1_pres_rmt_cap: int | None = Field(default=None, alias='24.1 PRES RMT CAP')
    s_24_1_pres_rmt_vig: int | None = Field(default=None, alias='24.1 PRES RMT VIG')
    s_24_1_pres_rmt_eva: int | None = Field(default=None, alias='24.1 PRES RMT EVA')
    s_24_2_pres_cal_cap: int | None = Field(default=None, alias='24.2 PRES CAL CAP')
    s_24_2_pres_cal_vig: int | None = Field(default=None, alias='24.2 PRES CAL VIG')
    s_24_2_pres_cal_eva: int | None = Field(default=None, alias='24.2 PRES CAL EVA')
    s_24_2_pres_oin_cap: int | None = Field(default=None, alias='24.2 PRES OIN CAP')
    s_24_2_pres_oin_vig: int | None = Field(default=None, alias='24.2 PRES OIN VIG')
    s_24_2_pres_oin_eva: int | None = Field(default=None, alias='24.2 PRES OIN EVA')
    s_24_2_pres_rmt_cap: int | None = Field(default=None, alias='24.2 PRES RMT CAP')
    s_24_2_pres_rmt_vig: int | None = Field(default=None, alias='24.2 PRES RMT VIG')
    s_24_2_pres_rmt_eva: int | None = Field(default=None, alias='24.2 PRES RMT EVA')
    s_25_1_pres_cal_cap: int | None = Field(default=None, alias='25.1 PRES CAL CAP')
    s_25_1_pres_cal_vig: int | None = Field(default=None, alias='25.1 PRES CAL VIG')
    s_25_1_pres_cal_eva: int | None = Field(default=None, alias='25.1 PRES CAL EVA')
    s_25_1_pres_oin_cap: int | None = Field(default=None, alias='25.1 PRES OIN CAP')
    s_25_1_pres_oin_vig: int | None = Field(default=None, alias='25.1 PRES OIN VIG')
    s_25_1_pres_oin_eva: int | None = Field(default=None, alias='25.1 PRES OIN EVA')
    s_25_1_pres_rmt_cap: int | None = Field(default=None, alias='25.1 PRES RMT CAP')
    s_25_1_pres_rmt_vig: int | None = Field(default=None, alias='25.1 PRES RMT VIG')
    s_25_1_pres_rmt_eva: int | None = Field(default=None, alias='25.1 PRES RMT EVA')
    s_25_2_pres_cal_cap: int | None = Field(default=None, alias='25.2 PRES CAL CAP')
    s_25_2_pres_cal_vig: int | None = Field(default=None, alias='25.2 PRES CAL VIG')
    s_25_2_pres_cal_eva: int | None = Field(default=None, alias='25.2 PRES CAL EVA')
    s_25_2_pres_oin_cap: int | None = Field(default=None, alias='25.2 PRES OIN CAP')
    s_25_2_pres_oin_vig: int | None = Field(default=None, alias='25.2 PRES OIN VIG')
    s_25_2_pres_oin_eva: int | None = Field(default=None, alias='25.2 PRES OIN EVA')
    s_25_2_pres_rmt_cap: int | None = Field(default=None, alias='25.2 PRES RMT CAP')
    s_25_2_pres_rmt_vig: int | None = Field(default=None, alias='25.2 PRES RMT VIG')
    s_25_2_pres_rmt_eva: int | None = Field(default=None, alias='25.2 PRES RMT EVA')
    s_26_1_pres_cal_cap: int | None = Field(default=None, alias='26.1 PRES CAL CAP')
    s_26_1_pres_cal_vig: int | None = Field(default=None, alias='26.1 PRES CAL VIG')
    s_26_1_pres_cal_eva: int | None = Field(default=None, alias='26.1 PRES CAL EVA')
    s_26_1_pres_oin_cap: int | None = Field(default=None, alias='26.1 PRES OIN CAP')
    s_26_1_pres_oin_vig: int | None = Field(default=None, alias='26.1 PRES OIN VIG')
    s_26_1_pres_oin_eva: int | None = Field(default=None, alias='26.1 PRES OIN EVA')
    s_26_1_pres_rmt_cap: int | None = Field(default=None, alias='26.1 PRES RMT CAP')
    s_26_1_pres_rmt_vig: int | None = Field(default=None, alias='26.1 PRES RMT VIG')
    s_26_1_pres_rmt_eva: int | None = Field(default=None, alias='26.1 PRES RMT EVA')
    s_26_2_pres_cal_cap: int | None = Field(default=None, alias='26.2 PRES CAL CAP')
    s_26_2_pres_cal_vig: int | None = Field(default=None, alias='26.2 PRES CAL VIG')
    s_26_2_pres_cal_eva: int | None = Field(default=None, alias='26.2 PRES CAL EVA')
    s_26_2_pres_oin_cap: int | None = Field(default=None, alias='26.2 PRES OIN CAP')
    s_26_2_pres_oin_vig: int | None = Field(default=None, alias='26.2 PRES OIN VIG')
    s_26_2_pres_oin_eva: int | None = Field(default=None, alias='26.2 PRES OIN EVA')
    s_26_2_pres_rmt_cap: int | None = Field(default=None, alias='26.2 PRES RMT CAP')
    s_26_2_pres_rmt_vig: int | None = Field(default=None, alias='26.2 PRES RMT VIG')
    s_26_2_pres_rmt_eva: int | None = Field(default=None, alias='26.2 PRES RMT EVA')
    s_27_1_pres_cal_cap: int | None = Field(default=None, alias='27.1 PRES CAL CAP')
    s_27_1_pres_cal_vig: int | None = Field(default=None, alias='27.1 PRES CAL VIG')
    s_27_1_pres_cal_eva: int | None = Field(default=None, alias='27.1 PRES CAL EVA')
    s_27_1_pres_oin_cap: int | None = Field(default=None, alias='27.1 PRES OIN CAP')
    s_27_1_pres_oin_vig: int | None = Field(default=None, alias='27.1 PRES OIN VIG')
    s_27_1_pres_oin_eva: int | None = Field(default=None, alias='27.1 PRES OIN EVA')
    s_27_1_pres_rmt_cap: int | None = Field(default=None, alias='27.1 PRES RMT CAP')
    s_27_1_pres_rmt_vig: int | None = Field(default=None, alias='27.1 PRES RMT VIG')
    s_27_1_pres_rmt_eva: int | None = Field(default=None, alias='27.1 PRES RMT EVA')
    s_27_2_pres_cal_cap: int | None = Field(default=None, alias='27.2 PRES CAL CAP')
    s_27_2_pres_cal_vig: int | None = Field(default=None, alias='27.2 PRES CAL VIG')
    s_27_2_pres_cal_eva: int | None = Field(default=None, alias='27.2 PRES CAL EVA')
    s_27_2_pres_oin_cap: int | None = Field(default=None, alias='27.2 PRES OIN CAP')
    s_27_2_pres_oin_vig: int | None = Field(default=None, alias='27.2 PRES OIN VIG')
    s_27_2_pres_oin_eva: int | None = Field(default=None, alias='27.2 PRES OIN EVA')
    s_27_2_pres_rmt_cap: int | None = Field(default=None, alias='27.2 PRES RMT CAP')
    s_27_2_pres_rmt_vig: int | None = Field(default=None, alias='27.2 PRES RMT VIG')
    s_27_2_pres_rmt_eva: int | None = Field(default=None, alias='27.2 PRES RMT EVA')
    s_28_1_pres_cal_cap: int | None = Field(default=None, alias='28.1 PRES CAL CAP')
    s_28_1_pres_cal_vig: int | None = Field(default=None, alias='28.1 PRES CAL VIG')
    s_28_1_pres_cal_eva: int | None = Field(default=None, alias='28.1 PRES CAL EVA')
    s_28_1_pres_oin_cap: int | None = Field(default=None, alias='28.1 PRES OIN CAP')
    s_28_1_pres_oin_vig: int | None = Field(default=None, alias='28.1 PRES OIN VIG')
    s_28_1_pres_oin_eva: int | None = Field(default=None, alias='28.1 PRES OIN EVA')
    s_28_1_pres_rmt_cap: int | None = Field(default=None, alias='28.1 PRES RMT CAP')
    s_28_1_pres_rmt_vig: int | None = Field(default=None, alias='28.1 PRES RMT VIG')
    s_28_1_pres_rmt_eva: int | None = Field(default=None, alias='28.1 PRES RMT EVA')
    s_28_2_pres_cal_cap: int | None = Field(default=None, alias='28.2 PRES CAL CAP')
    s_28_2_pres_cal_vig: int | None = Field(default=None, alias='28.2 PRES CAL VIG')
    s_28_2_pres_cal_eva: int | None = Field(default=None, alias='28.2 PRES CAL EVA')
    s_28_2_pres_oin_cap: int | None = Field(default=None, alias='28.2 PRES OIN CAP')
    s_28_2_pres_oin_vig: int | None = Field(default=None, alias='28.2 PRES OIN VIG')
    s_28_2_pres_oin_eva: int | None = Field(default=None, alias='28.2 PRES OIN EVA')
    s_28_2_pres_rmt_cap: int | None = Field(default=None, alias='28.2 PRES RMT CAP')
    s_28_2_pres_rmt_vig: int | None = Field(default=None, alias='28.2 PRES RMT VIG')
    s_28_2_pres_rmt_eva: int | None = Field(default=None, alias='28.2 PRES RMT EVA')
    s_29_1_pres_cal_cap: int | None = Field(default=None, alias='29.1 PRES CAL CAP')
    s_29_1_pres_cal_vig: int | None = Field(default=None, alias='29.1 PRES CAL VIG')
    s_29_1_pres_cal_eva: int | None = Field(default=None, alias='29.1 PRES CAL EVA')
    s_29_1_pres_oin_cap: int | None = Field(default=None, alias='29.1 PRES OIN CAP')
    s_29_1_pres_oin_vig: int | None = Field(default=None, alias='29.1 PRES OIN VIG')
    s_29_1_pres_oin_eva: int | None = Field(default=None, alias='29.1 PRES OIN EVA')
    s_29_1_pres_rmt_cap: int | None = Field(default=None, alias='29.1 PRES RMT CAP')
    s_29_1_pres_rmt_vig: int | None = Field(default=None, alias='29.1 PRES RMT VIG')
    s_29_1_pres_rmt_eva: int | None = Field(default=None, alias='29.1 PRES RMT EVA')
    s_29_2_pres_cal_cap: int | None = Field(default=None, alias='29.2 PRES CAL CAP')
    s_29_2_pres_cal_vig: int | None = Field(default=None, alias='29.2 PRES CAL VIG')
    s_29_2_pres_cal_eva: int | None = Field(default=None, alias='29.2 PRES CAL EVA')
    s_29_2_pres_oin_cap: int | None = Field(default=None, alias='29.2 PRES OIN CAP')
    s_29_2_pres_oin_vig: int | None = Field(default=None, alias='29.2 PRES OIN VIG')
    s_29_2_pres_oin_eva: int | None = Field(default=None, alias='29.2 PRES OIN EVA')
    s_29_2_pres_rmt_cap: int | None = Field(default=None, alias='29.2 PRES RMT CAP')
    s_29_2_pres_rmt_vig: int | None = Field(default=None, alias='29.2 PRES RMT VIG')
    s_29_2_pres_rmt_eva: int | None = Field(default=None, alias='29.2 PRES RMT EVA')
    s_30_1_pres_cal_cap: int | None = Field(default=None, alias='30.1 PRES CAL CAP')
    s_30_1_pres_cal_vig: int | None = Field(default=None, alias='30.1 PRES CAL VIG')
    s_30_1_pres_cal_eva: int | None = Field(default=None, alias='30.1 PRES CAL EVA')
    s_30_1_pres_oin_cap: int | None = Field(default=None, alias='30.1 PRES OIN CAP')
    s_30_1_pres_oin_vig: int | None = Field(default=None, alias='30.1 PRES OIN VIG')
    s_30_1_pres_oin_eva: int | None = Field(default=None, alias='30.1 PRES OIN EVA')
    s_30_1_pres_rmt_cap: int | None = Field(default=None, alias='30.1 PRES RMT CAP')
    s_30_1_pres_rmt_vig: int | None = Field(default=None, alias='30.1 PRES RMT VIG')
    s_30_1_pres_rmt_eva: int | None = Field(default=None, alias='30.1 PRES RMT EVA')
    s_30_2_pres_cal_cap: int | None = Field(default=None, alias='30.2 PRES CAL CAP')
    s_30_2_pres_cal_vig: int | None = Field(default=None, alias='30.2 PRES CAL VIG')
    s_30_2_pres_cal_eva: int | None = Field(default=None, alias='30.2 PRES CAL EVA')
    s_30_2_pres_oin_cap: int | None = Field(default=None, alias='30.2 PRES OIN CAP')
    s_30_2_pres_oin_vig: int | None = Field(default=None, alias='30.2 PRES OIN VIG')
    s_30_2_pres_oin_eva: int | None = Field(default=None, alias='30.2 PRES OIN EVA')
    s_30_2_pres_rmt_cap: int | None = Field(default=None, alias='30.2 PRES RMT CAP')
    s_30_2_pres_rmt_vig: int | None = Field(default=None, alias='30.2 PRES RMT VIG')
    s_30_2_pres_rmt_eva: int | None = Field(default=None, alias='30.2 PRES RMT EVA')

    __pydantic_validator__ = field_validator("*", mode='before')(valida_valores_vazios)


class DadosEad2(BaseModel):
    model_config = ConfigDict(populate_by_name=True)
    dias: int | None = Field(default=None, alias='Dias')
    s_18_2_ead2_oin_cap: int | None = Field(default=None, alias='18.2 EAD2 OIN CAP')
    s_18_2_ead2_oin_vig: int | None = Field(default=None, alias='18.2 EAD2 OIN VIG')
    s_18_2_ead2_oin_eva: int | None = Field(default=None, alias='18.2 EAD2 OIN EVA')
    s_19_1_ead2_oin_cap: int | None = Field(default=None, alias='19.1 EAD2 OIN CAP')
    s_19_1_ead2_oin_vig: int | None = Field(default=None, alias='19.1 EAD2 OIN VIG')
    s_19_1_ead2_oin_eva: int | None = Field(default=None, alias='19.1 EAD2 OIN EVA')
    s_19_2_ead2_oin_cap: int | None = Field(default=None, alias='19.2 EAD2 OIN CAP')
    s_19_2_ead2_oin_vig: int | None = Field(default=None, alias='19.2 EAD2 OIN VIG')
    s_19_2_ead2_oin_eva: int | None = Field(default=None, alias='19.2 EAD2 OIN EVA')
    s_20_1_ead2_oin_cap: int | None = Field(default=None, alias='20.1 EAD2 OIN CAP')
    s_20_1_ead2_oin_vig: int | None = Field(default=None, alias='20.1 EAD2 OIN VIG')
    s_20_1_ead2_oin_eva: int | None = Field(default=None, alias='20.1 EAD2 OIN EVA')
    s_20_2_ead2_oin_cap: int | None = Field(default=None, alias='20.2 EAD2 OIN CAP')
    s_20_2_ead2_oin_vig: int | None = Field(default=None, alias='20.2 EAD2 OIN VIG')
    s_20_2_ead2_oin_eva: int | None = Field(default=None, alias='20.2 EAD2 OIN EVA')
    s_21_1_ead2_oin_cap: int | None = Field(default=None, alias='21.1 EAD2 OIN CAP')
    s_21_1_ead2_oin_vig: int | None = Field(default=None, alias='21.1 EAD2 OIN VIG')
    s_21_1_ead2_oin_eva: int | None = Field(default=None, alias='21.1 EAD2 OIN EVA')
    s_21_2_ead2_oin_cap: int | None = Field(default=None, alias='21.2 EAD2 OIN CAP')
    s_21_2_ead2_oin_vig: int | None = Field(default=None, alias='21.2 EAD2 OIN VIG')
    s_21_2_ead2_oin_eva: int | None = Field(default=None, alias='21.2 EAD2 OIN EVA')
    s_22_1_ead2_oin_cap: int | None = Field(default=None, alias='22.1 EAD2 OIN CAP')
    s_22_1_ead2_oin_vig: int | None = Field(default=None, alias='22.1 EAD2 OIN VIG')
    s_22_1_ead2_oin_eva: int | None = Field(default=None, alias='22.1 EAD2 OIN EVA')
    s_22_2_ead2_oin_cap: int | None = Field(default=None, alias='22.2 EAD2 OIN CAP')
    s_22_2_ead2_oin_vig: int | None = Field(default=None, alias='22.2 EAD2 OIN VIG')
    s_22_2_ead2_oin_eva: int | None = Field(default=None, alias='22.2 EAD2 OIN EVA')
    s_23_1_ead2_oin_cap: int | None = Field(default=None, alias='23.1 EAD2 OIN CAP')
    s_23_1_ead2_oin_vig: int | None = Field(default=None, alias='23.1 EAD2 OIN VIG')
    s_23_1_ead2_oin_eva: int | None = Field(default=None, alias='23.1 EAD2 OIN EVA')
    s_23_2_ead2_oin_cap: int | None = Field(default=None, alias='23.2 EAD2 OIN CAP')
    s_23_2_ead2_oin_vig: int | None = Field(default=None, alias='23.2 EAD2 OIN VIG')
    s_23_2_ead2_oin_eva: int | None = Field(default=None, alias='23.2 EAD2 OIN EVA')
    s_24_1_ead2_oin_cap: int | None = Field(default=None, alias='24.1 EAD2 OIN CAP')
    s_24_1_ead2_oin_vig: int | None = Field(default=None, alias='24.1 EAD2 OIN VIG')
    s_24_1_ead2_oin_eva: int | None = Field(default=None, alias='24.1 EAD2 OIN EVA')
    s_24_2_ead2_oin_cap: int | None = Field(default=None, alias='24.2 EAD2 OIN CAP')
    s_24_2_ead2_oin_vig: int | None = Field(default=None, alias='24.2 EAD2 OIN VIG')
    s_24_2_ead2_oin_eva: int | None = Field(default=None, alias='24.2 EAD2 OIN EVA')
    s_25_1_ead2_oin_cap: int | None = Field(default=None, alias='25.1 EAD2 OIN CAP')
    s_25_1_ead2_oin_vig: int | None = Field(default=None, alias='25.1 EAD2 OIN VIG')
    s_25_1_ead2_oin_eva: int | None = Field(default=None, alias='25.1 EAD2 OIN EVA')
    s_25_2_ead2_oin_cap: int | None = Field(default=None, alias='25.2 EAD2 OIN CAP')
    s_25_2_ead2_oin_vig: int | None = Field(default=None, alias='25.2 EAD2 OIN VIG')
    s_25_2_ead2_oin_eva: int | None = Field(default=None, alias='25.2 EAD2 OIN EVA')
    s_26_1_ead2_oin_cap: int | None = Field(default=None, alias='26.1 EAD2 OIN CAP')
    s_26_1_ead2_oin_vig: int | None = Field(default=None, alias='26.1 EAD2 OIN VIG')
    s_26_1_ead2_oin_eva: int | None = Field(default=None, alias='26.1 EAD2 OIN EVA')
    s_26_2_ead2_oin_cap: int | None = Field(default=None, alias='26.2 EAD2 OIN CAP')
    s_26_2_ead2_oin_vig: int | None = Field(default=None, alias='26.2 EAD2 OIN VIG')
    s_26_2_ead2_oin_eva: int | None = Field(default=None, alias='26.2 EAD2 OIN EVA')
    s_27_1_ead2_oin_cap: int | None = Field(default=None, alias='27.1 EAD2 OIN CAP')
    s_27_1_ead2_oin_vig: int | None = Field(default=None, alias='27.1 EAD2 OIN VIG')
    s_27_1_ead2_oin_eva: int | None = Field(default=None, alias='27.1 EAD2 OIN EVA')
    s_27_2_ead2_oin_cap: int | None = Field(default=None, alias='27.2 EAD2 OIN CAP')
    s_27_2_ead2_oin_vig: int | None = Field(default=None, alias='27.2 EAD2 OIN VIG')
    s_27_2_ead2_oin_eva: int | None = Field(default=None, alias='27.2 EAD2 OIN EVA')
    s_28_1_ead2_oin_cap: int | None = Field(default=None, alias='28.1 EAD2 OIN CAP')
    s_28_1_ead2_oin_vig: int | None = Field(default=None, alias='28.1 EAD2 OIN VIG')
    s_28_1_ead2_oin_eva: int | None = Field(default=None, alias='28.1 EAD2 OIN EVA')
    s_28_2_ead2_oin_cap: int | None = Field(default=None, alias='28.2 EAD2 OIN CAP')
    s_28_2_ead2_oin_vig: int | None = Field(default=None, alias='28.2 EAD2 OIN VIG')
    s_28_2_ead2_oin_eva: int | None = Field(default=None, alias='28.2 EAD2 OIN EVA')
    s_29_1_ead2_oin_cap: int | None = Field(default=None, alias='29.1 EAD2 OIN CAP')
    s_29_1_ead2_oin_vig: int | None = Field(default=None, alias='29.1 EAD2 OIN VIG')
    s_29_1_ead2_oin_eva: int | None = Field(default=None, alias='29.1 EAD2 OIN EVA')
    s_29_2_ead2_oin_cap: int | None = Field(default=None, alias='29.2 EAD2 OIN CAP')
    s_29_2_ead2_oin_vig: int | None = Field(default=None, alias='29.2 EAD2 OIN VIG')
    s_29_2_ead2_oin_eva: int | None = Field(default=None, alias='29.2 EAD2 OIN EVA')
    s_30_1_ead2_oin_cap: int | None = Field(default=None, alias='30.1 EAD2 OIN CAP')
    s_30_1_ead2_oin_vig: int | None = Field(default=None, alias='30.1 EAD2 OIN VIG')
    s_30_1_ead2_oin_eva: int | None = Field(default=None, alias='30.1 EAD2 OIN EVA')
    s_30_2_ead2_oin_cap: int | None = Field(default=None, alias='30.2 EAD2 OIN CAP')
    s_30_2_ead2_oin_vig: int | None = Field(default=None, alias='30.2 EAD2 OIN VIG')
    s_30_2_ead2_oin_eva: int | None = Field(default=None, alias='30.2 EAD2 OIN EVA')

    __pydantic_validator__ = field_validator("*", mode='before')(valida_valores_vazios)


# dici = {'Dias': -100, '16.2': 0}
# dados = DadosPorSemestre(**dici)
# print(dados.model_dump())
# print(dados.model_dump(by_alias=True))
# dici = {'Dias': -100, '18.2 SEMI CAL CAP': 1}
# dici2 = {'dias': -100, 's_18_2_semi_cal_cap': 1}
# dados = DadosSemi(**dici)
# dados2 = DadosSemi(**dici2)
# print(dados2.model_dump_json(by_alias=True))
